
# Define UI 
shinyUI(dashboardPage(
    skin = 'yellow',
    
    dashboardHeader(title = "Movie Analysis"),
    dashboardSidebar(
        sidebarUserPanel('Jack Ferreri'),
        sidebarMenu(menuItem('Home', tabName = 'Home', icon = icon('home')),
                    menuItem('Genre', tabName = 'Genre', icon = icon('bookmark')),
                    menuItem('Duration', tabName = 'Duration', icon = icon('clock')),
                    menuItem('Actors & Directors', tabName = 'Actors', icon = icon('user')),
                    menuItem('Country', tabName = 'Country', icon = icon('globe')),
                    menuItem('Data', tabName = 'data', icon = icon('database')),
                    menuItem('Notes', tabName = 'Notes', icon = icon('film'))
        ),
        sliderInput(
            "daterange", "Date Range:",
            min = 2005,
            max = 2019,
            value = c(2005, 2019),
            sep = ''
        )
    ),
    dashboardBody(
        tabItems(
            tabItem(tabName = 'Home',
                    fluidPage(
                        h1(strong("What Types of Movies Will Maximize Subscriptions?")),
                        img(src='streamingwars.png', align = 'center', height="65%", width="65%"),
                        align = 'center'),
                    p("Source: Raab, Mike.", em("OneZero"), "Medium, 31 Oct. 2019, onezero.medium.com/everyones-wrong-about-the-streaming-wars-95f1eb717a90.", align = "center"),
                    br(),
                    p(em(strong("As companies with streaming services seek to maximize subscriptions under increasing competition, what movie content should they acquire and/or produce?"))),
                    p("I designed this Shiny app to begin answering this question. The app explores recent trends in movie popularity among several variables. For purposes of this analysis, popularity is measured by viewers' IMDb ratings (on a scale of 1-10) and worldwide gross income (USD). Analysis is based on data obtained from the", tags$a(href="https://www.kaggle.com/stefanoleone992/imdb-extensive-dataset?select=IMDb+movies.csv", "IMDb movies extensive dataset"), "from", tags$a(href="https://www.kaggle.com/", "Kaggle"), ", which in turn was scraped from the popular movie website", tags$a(href="https://www.imdb.com/", "IMDb"), "."),
                    p("While the dataset includes titles dating back to the early 1900s, this analysis only considered titles released since 2005. I wish to focus on how viewers feel about movies released in recent years as streaming has become increasingly popular. The ability to stream from multiple (and mobile) devices has made movie consumption more convenient than ever, with more people opting for the couch over the big screen. I suspect that viewer preferences may have changed in recent years due to this increased accessibility."),
                    fluidRow(valueBoxOutput("titles"),
                             valueBoxOutput("votes"),
                             valueBoxOutput("years"))),
            tabItem(tabName = 'Genre',
                    h1(strong("Which Genres are Most Popular?")),
                    p('This page explores the most popular genres since 2005.'),
                    p(em("Rating"), "measures a viewer's IMDb rating between 1-10."),
                    p(em('Income'), "measures a movie's gross income in USD."),
                    fluidRow(box(plotOutput("genre_rating"), width = 6),
                             box(plotOutput("genre_income"), width = 6)),
                             plotOutput("genre_distribution"),
                             plotOutput("genre_trend")),
            tabItem(tabName = 'Duration',
                    h1(strong("Do Longer Movies Get Higher Ratings?")),
                    p('This page explores movie popularity in terms of their duration.'),
                    p(em("Rating"), "measures a viewer's IMDb rating between 1-10."),
                    p(em('Income'), "measures a movie's worldwide gross income in USD."),
                    p(em('Duration'), "measures a movie's length in minutes."),
                    p("Movies less than 90 minutes are defined as", em('short.')),
                    p("Movies between 90-120 minutes are defined as", em('medium.')),
                    p("Movies greater than 120 minutes are defined as", em('long.')),
                    fluidRow(box(plotOutput("duration_mean"), width = 6),
                             box(plotOutput("duration_v_rating"), width = 6)),
                    fluidRow(box(plotOutput("duration_rating"), width = 4),
                             box(plotOutput("duration_income"), width = 4),
                             box(plotOutput("duration_distribution"), width = 4)),
                    fluidRow(box(plotOutput("duration_rating_trend"), width = 6),
                             box(plotOutput("duration_income_trend"), width = 6))),
            tabItem(tabName = 'Actors',
                    h1(strong("Who Produces the Most Popular U.S. Movies?")),
                    p('This page explores actors and directors that produce the most popular U.S. movies.'),
                    p('Only actors who have appeared in', em('at least 10 movies'), '(1,569 actors) were included in this analysis.'),
                    p('Only directors who have directed', em('at least 5 movies'), '(191 directors) were included in this analysis.'),
                    p(em("Rating"), "measures a viewer's IMDb rating between 1-10."),
                    p(em('Income'), "measures a movie's worldwide gross income in USD."),
                    fluidRow(box(plotOutput("actors_rating"), width = 6),
                             box(plotOutput("actors_income"), width = 6)),
                    fluidRow(box(plotOutput("director_rating"), width = 6),
                             box(plotOutput("director_income"), width = 6))),
            tabItem(tabName = 'Country',
                    h1(strong("Which Countries Have the Most Popular Movies?")),
                    p('This page explores which countries have the most popular movies.'),
                    p('Only countries with', em('at least 100 movies'), 'were included in this analysis (23 countries).'),
                    p(em("Rating"), "measures a viewer's IMDb rating between 1-10."),
                    p(em('Income'), "measures a movie's worldwide gross income in USD."),
                    fluidRow(box(plotOutput("country_rating"), width = 6),
                             box(plotOutput("country_income"), width = 6)),
                             plotOutput("country_trend")),
            tabItem(tabName = 'data',
                    fluidRow(box(
                             title = "Search Complete Dataset",
                             status = "primary",
                             solidHeader = TRUE,
                             DT::dataTableOutput("table"),
                             width = 12))),
            tabItem(tabName = 'Notes',
                    h1(strong('Takeaways and Topics for Further Exploration')),
                    p('Please visit my blog post for further discussion on this topic.'),
                    h1(strong('Learn More About Me')),
                    p(tags$a(href="https://www.linkedin.com/in/jack-g-ferreri", "LinkedIn")),
                    p(tags$a(href="https://github.com/Jboy07", "GitHub")))
        )
    )
))

